# Generated by Django 2.2.3 on 2019-08-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0008_user_keys_last_used'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Keys',
            new_name='UserKey',
        ),
    ]
